# Generated by Django 6.0.8 on 2026-09-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=8, unique=True)),
                ('white', models.CharField(blank=True, max_length=40, null=True)),
                ('black', models.CharField(blank=True, max_length=40, null=True)),
                ('fen', models.TextField(default='')),
            ],
        ),
    ]
